Bot: Label docs-only changes `no-changelog`
gravitational/shared-workflows pull request #278
Opened 2024-10-09 17:32 UTC by ptgott

Docs-only changes usually do not require a changelog entry. Automatically add the `no-changelog` label for docs-only changes so docs authors do not receive unnecessary notifications about missing `no-changelog` labels and workflow failures for docs-only pull requests.

2024-10-09 17:34 UTC, ptgott commented
Actually, might make sense to add file-checking logic to the changelog workflow instead of this indirect route.

2024-10-09 18:36 UTC, zmb3 commented
> Actually, might make sense to add file-checking logic to the changelog workflow instead of using this indirect route.

+1

We control both the labeling workflow and the check for a changelog entry. 

I'd rather have the changelog check simply not care about changelogs for docs changes.

2025-01-31 22:12 UTC, zmb3 approved these changes

2025-02-03 21:59 UTC, fheinecke requested changes
This needs changes to maintain compatibility with release tooling, as discussed on slack here: https://gravitational.slack.com/archives/C0351AUPJ8K/p1738617752346529

2025-02-06 18:26 UTC, fheinecke approved these changes
LGTM outside of magic string

2025-02-06 18:26 UTC, fheinecke commented on bot/internal/bot/label.go
> +		labels = append(labels, "no-changelog")
Can you change the value to [this constant](https://github.com/gravitational/shared-workflows/blob/main/bot/internal/bot/changelog.go#L30)?

2025-02-06 18:26 UTC, fheinecke commented on bot/internal/bot/label_test.go
> +			labels: []string{"documentation", "no-changelog", string(small)},
Same as above (const vs magic string)

2025-02-06 18:31 UTC, ptgott commented on bot/internal/bot/label_test.go
> +			labels: []string{"documentation", "no-changelog", string(small)},
Fixed in 9078af911d64ccf6459280851bf0fb783acc7258

2025-02-06 18:31 UTC, ptgott commented on bot/internal/bot/label.go
> +		labels = append(labels, "no-changelog")
Fixed in 9078af911d64ccf6459280851bf0fb783acc7258

2025-02-06 18:35 UTC, merged